---
id: Service_UrlShortener
name: Service_UrlShortener
full: URL shortening library
description: Interfaces to various URL shortening services.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Service_UrlShortener
authors:
  -
    name: Michael J Rubinsky
    user: mrubinsk
    email: mrubinsk@horde.org
    active: true
    role: lead
version:
  release: 2.0.4
  api: 1.0.0
state:
  release: stable
  api: stable
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Url: ^2
      pear.horde.org/Horde_Http: ^2
